# Generated by Django 5.1.6 on 2025-02-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('imdb_rating', models.FloatField()),
                ('directors', models.CharField(max_length=255)),
                ('cast', models.TextField()),
                ('plot_summary', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('imdb_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
